services:
  - type: web
    name: tue-photonics
    env: node
    plan: free
    region: frankfurt

    buildCommand: |
      npm ci
      npm run build
      cd server && npm ci --omit=dev

    startCommand: cd server && node server.js

    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PAYLOAD_SECRET
        generateValue: true
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_Ch4uga0QmOZU@ep-holy-snow-agw13no5-pooler.c-2.eu-central-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
      - key: DATABASE_SSL
        value: "true"
      - key: SERVER_URL
        value: "https://tue-photonics.onrender.com"

      # опционально для первичного сидирования админа:
      - key: PAYLOAD_SEED_ADMIN_EMAIL
        value: admin@tue.nl
      - key: PAYLOAD_SEED_ADMIN_PASSWORD
        value: YourStrongPassword123!
